openapi: 3.0.0
info:
  title: Denefits
  version: '1.0'
  description: Denefits Business APIs
servers:
  - url: 'https://api.denefits.com:8005'
paths:
  /provider:
    get:
      summary: Get Providers registered with your account or a particular Provider.
      tags:
        - Providers
      operationId: get-providers
      description: |
        ## GET API -
        This API returns all the providers registered with the account using **Provider token in headers** and you can get a particular provider under your account using **Provider Id in query params** with the same token in headers.
      responses:
        '200':
          description: A Successfull Response
          headers: {}
        '400':
          description: Bad Request
        '401':
          description: Authentication Failed
        '402':
          description: ' Request Faild'
        '500':
          description: Internal Server Error
      parameters:
        - schema:
            type: string
          in: query
          name: provider_id
          description: To get a particular provider
        - schema:
            type: string
          in: header
          name: token
          description: To get all providers registered with this account
          required: true
    parameters: []
    post:
      summary: To Add a new business with your account
      operationId: post-provider
      responses:
        '200':
          description: A Successfull Response
        '400':
          description: Bad Request
        '401':
          description: Authentication Failed
        '402':
          description: Request Failed
        '500':
          description: Internal Server Error
      description: |-
        ## POST API -
        This API creates a new business under the provider account by using **provider token in headers** and a **new business object in body**.
      parameters:
        - schema:
            type: string
          in: header
          name: token
          required: true
      tags:
        - Providers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                phone:
                  type: string
              required:
                - email
                - first_name
                - last_name
                - phone
            examples:
              example:
                value:
                  email: Charles.one@bridgingtech.com
                  first_name: Charles
                  last_name: One
                  phone: '1234567890'
        description: Business Object
  /plans:
    get:
      summary: Get plans for the Finance Amount
      tags:
        - Plans
      responses:
        '200':
          description: A Successfull Response
        '400':
          description: Bad Request
        '401':
          description: Authentication Failed
        '402':
          description: Request Failed
        '500':
          description: Internal Server Error
      operationId: get-plans
      description: |-
        ## GET API -
        This API returns all the plans for the given **Financed Amount in query params** under the provider having**token in headers** and **Provider Id in query params**
      parameters:
        - schema:
            type: string
          in: query
          name: financed_amount
          description: Amount to Finance
          required: true
        - schema:
            type: string
          in: header
          name: token
          description: Provider token
          required: true
        - schema:
            type: string
          in: query
          name: provider_id
          description: For a particular provider
          required: true
  /finance_customer:
    post:
      summary: To Finance a Customer
      operationId: post-finance_customer
      responses:
        '200':
          description: A Successfull Response
        '400':
          description: Bad Request
        '401':
          description: Authentication Failed
        '402':
          description: Request Failed
        '500':
          description: Internal Server Error
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: A Provider Token
      description: |-
        ## POST API -
        This API is to finance a customer under the provider account by using **provider token in headers** and a **customer object in body**.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                provider_id:
                  type: string
                financed_amount:
                  type: string
                month:
                  type: string
                start_date:
                  type: string
                customer_email:
                  type: string
                customer_first_name:
                  type: string
                customer_last_name:
                  type: string
                customer_mobile:
                  type: string
              required:
                - provider_id
                - financed_amount
                - month
                - start_date
                - customer_email
                - customer_first_name
                - customer_last_name
                - customer_mobile
            examples:
              example:
                value:
                  provider_id: '1234'
                  financed_amount: '1000'
                  month: '12'
                  start_date: '2020-04-30'
                  customer_email: charles.ones@bridgingtech.com
                  customer_first_name: Charles
                  customer_last_name: One
                  customer_mobile: +1-1234567890
        description: Customer Object
      tags:
        - Finance
  /zipcode:
    get:
      summary: To get all the Cities for the ZipCode
      tags:
        - ZipCode
      responses:
        '200':
          description: A Successfull Response
        '400':
          description: Bad Request
        '401':
          description: Authentication Failed
        '402':
          description: Request Failed
        '500':
          description: Internal Server Error
      operationId: get-zipcode
      description: |-
        ## GET API -
        This API returns all the cities for the given **zipcode in query params** under the **provider token in headers**
      parameters:
        - schema:
            type: string
          in: query
          required: true
          name: zipcode
          description: ZipCode
        - schema:
            type: string
          in: header
          name: token
          required: true
          description: A Provider Token
components:
  schemas: {}
