openapi: 3.0.0
info:
  title: Denefits
  version: '1.0'
  description: Denefits Business APIs
servers:
  - url: 'https://api.denefits.com:8005'
paths:
  /provider:
    get:
      summary: Get Providers registered with your account or a particular Provider.
      tags:
        - Providers
      operationId: get-providers
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples: {}
      description: |
        ## GET API -
        This API returns all the providers registered with the account using **provider token in headers** and you can get a particular provider under your account using **provider_id in query params**.
      responses:
        '200':
          description: A Successfull Response
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '400':
          description: Bad Request
        '401':
          description: Authentication Failed
        '402':
          description: ' Request Faild'
        '500':
          description: Internal Server Error
      parameters:
        - schema:
            type: string
          in: query
          name: provider_id
          description: To get a particular provider
        - schema:
            type: string
          in: header
          name: token
          description: To get all providers registered with this account
    parameters: []
    post:
      summary: To Add a new business with your account
      operationId: post-provider
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string
                  phone:
                    type: string
              examples:
                example:
                  value:
                    token: test_token
                    email: Charles.one@bridgingtech.com
                    first_name: Charles
                    last_name: One
                    phone: '1234567890'
      description: |-
        ## POST API -
        This API creates a new provider with the account of using **token in headers** and a **new request object in body**.
      parameters:
        - schema:
            type: string
          in: header
          name: token
      tags:
        - Providers
  /plans:
    get:
      summary: Get plans
      tags:
        - Plans
      responses:
        '200':
          description: OK
      operationId: get-plans
      description: Get plans for making contract.
      parameters:
        - schema:
            type: string
          in: header
          name: token
      requestBody:
        description: Provider Id of the provider.
        content:
          application/json:
            schema:
              type: object
              properties:
                provider_id:
                  type: number
components:
  schemas:
    Plans:
      title: Plans
      type: array
      x-examples:
        example-1: []
      items:
        $ref: '#/components/schemas/Plan'
      x-tags:
        - Plans
    Plan:
      title: Plan
      type: object
      properties:
        month:
          type: number
        recurring_amount:
          type: number
