openapi: 3.0.0
info:
  title: Finance
  description: Denefits Business APIs
servers:
  - url: 'https://api.denefits.com:8005'
paths:
  /v1/finance_customer:
    post:
      summary: To Finance a Customer
      operationId: post-finance_customer
      responses:
        '200':
          description: A Successfull Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        contract_id:
                          type: number
                  message:
                    type: string
              examples:
                Customer Financed Successfully:
                  value:
                    data:
                      contract_id: 16633
                    message: Customer Financed Successfully
            application/xml:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        contract_id:
                          type: number
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    data:
                      contract_id: 16633
                    message: Customer Financed Successfully
            multipart/form-data:
              schema:
                type: object
                properties: {}
              examples:
                example-1: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: {}
                  message:
                    type: string
              examples:
                If token is missing in headers:
                  value:
                    data: []
                    message: "Mandatory parameter 'token' is missing."
                If any of the required_field is missing:
                  value:
                    data: []
                    message: '"required_field" is required'
                If financed_amount is empty or is not a number:
                  value:
                    data: []
                    message: '"financed_amount" must be a number'
                If months are not valid:
                  value:
                    message: Number of payments or financed amount are not valid
                If start_date is empty or not a valid date.:
                  value:
                    data: []
                    message: '"start_date" must be a valid date'
                If customer_email is empty:
                  value:
                    data: []
                    message: '"customer_email" is not allowed to be empty'
                If customer_email is not a valid email:
                  value:
                    data: []
                    message: '"customer_email" must be a valid email'
                If customer_mobile is invalid:
                  value:
                    data: []
                    message: 'Invalid "customer_mobile" provided '
                Somethng went wrong:
                  value:
                    message: Contract not financed
        '401':
          description: Authentication Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: {}
                  message:
                    type: string
              examples:
                If token is wrong:
                  value:
                    data: []
                    message: Invalid auth token provided
                If provider_id is wrong:
                  value:
                    message: Provider does not belong to this partner
        '402':
          description: Request Failed
        '500':
          description: Internal Server Error
      parameters:
        - schema:
            type: string
          in: header
          name: token
          description: A Provider Token
      description: |-
        ### POST Method -
        This API is to finance a customer under the provider account by using **provider token in headers** and a **customer object in body**.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
            examples:
              example:
                value:
                  provider_id: '1234'
                  financed_amount: '1000'
                  month: '12'
                  start_date: '2020-04-30'
                  customer_email: charles.ones@bridgingtech.com
                  customer_first_name: Charles
                  customer_last_name: One
                  customer_mobile: '1234567890'
        description: Customer Object
      tags:
        - Finance
    parameters: []
components:
  schemas:
    Customer:
      title: Customer
      type: object
      x-examples: {}
      description: Customer Object
      properties:
        provider_id:
          type: string
        financed_amount:
          type: string
        month:
          type: string
        start_date:
          type: string
        customer_email:
          type: string
        customer_first_name:
          type: string
        customer_last_name:
          type: string
        customer_phone:
          type: string
      required:
        - provider_id
        - financed_amount
        - month
        - start_date
        - customer_email
        - customer_first_name
        - customer_phone
