openapi: 3.0.0
info:
  title: Plans
  description: This Section is related with Financing Plans.
servers:
  - url: 'https://api.denefits.com:8005'
paths:
  /v1/plans:
    get:
      summary: Get plans for the Finance Amount
      tags:
        - Plans
      responses:
        '200':
          description: A Successfull Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        financing_plans:
                          type: array
                          items:
                            type: object
                            properties:
                              contract_creation_fee:
                                type: number
                              downpayment_transaction_fee:
                                type: number
                              interest_rate:
                                type: number
                              month:
                                type: number
                              recurring_amount:
                                type: number
                              recurring_transaction_fee:
                                type: number
                              upfront_fee:
                                type: number
                  message:
                    type: string
              examples:
                A Successfull Response:
                  value:
                    data:
                      financing_plans:
                        - contract_creation_fee: 30
                          downpayment_transaction_fee: 3
                          interest_rate: 16.99
                          month: 12
                          recurring_amount: 112.37
                          recurring_transaction_fee: 3.37
                          upfront_fee: 112.37
                        - contract_creation_fee: 30
                          downpayment_transaction_fee: 3
                          interest_rate: 16.99
                          month: 13
                          recurring_amount: 105.82
                          recurring_transaction_fee: 3.17
                          upfront_fee: 105.82
                        - contract_creation_fee: 30
                          downpayment_transaction_fee: 3
                          interest_rate: 16.99
                          month: 14
                          recurring_amount: 100.16
                          recurring_transaction_fee: 3
                          upfront_fee: 100.16
                        - contract_creation_fee: 30
                          downpayment_transaction_fee: 3
                          interest_rate: 16.99
                          month: 15
                          recurring_amount: 95.23
                          recurring_transaction_fee: 3
                          upfront_fee: 95.23
                    message: Suceess
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: {}
                  message:
                    type: string
              examples:
                If token is missing in headers:
                  value:
                    data: []
                    message: "Mandatory parameter 'token' is missing."
                If provider_id is missing in query params:
                  value:
                    data: []
                    message: "Mandatory parameter 'provider_id' is missing."
                If financed amount is missing or less than 0:
                  value:
                    data: []
                    message: '"financed_amount" is required'
                If financed_amount is not a valid amount:
                  value:
                    data: []
                    message: '"financed_amount" must be a safe number'
        '401':
          description: Authentication Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: {}
                  message:
                    type: string
              examples:
                If token is wrong:
                  value:
                    data: []
                    message: Invalid auth token provided
                if provider_id is wrong:
                  value:
                    message: Provider does not belong to this partner
        '402':
          description: Request Failed
        '500':
          description: Internal Server Error
      operationId: get-plans
      description: |-
        ### GET Method-
        This API returns all the plans for the given **Financed Amount in query params** under the provider having **token in headers** and **Provider Id in query params**
      parameters:
        - schema:
            type: string
          in: query
          name: financed_amount
          description: Amount to Finance
          required: true
        - schema:
            type: string
          in: header
          name: token
          description: Provider token
          required: true
        - schema:
            type: string
          in: query
          name: provider_id
          description: For a particular provider
          required: true
    parameters: []
components:
  schemas: {}
