openapi: 3.0.0
info:
  title: Zipcode
  description: This Section is related with Cities Information.
paths:
  /v1/zipcode:
    get:
      summary: To get all the Cities for the ZipCode
      tags:
        - ZipCode
      responses:
        '200':
          description: A Successfull Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        zipcode_array:
                          type: array
                          items:
                            type: object
                            properties:
                              city:
                                type: string
                              city_id:
                                type: number
                              country_code:
                                type: string
                              country_name:
                                type: string
                              state_name:
                                type: string
                              zip:
                                type: number
                  message:
                    type: string
              examples:
                A Successfull Response:
                  value:
                    data:
                      zipcode_array:
                        - city: Schenectady
                          city_id: 4139
                          country_code: US
                          country_name: United States
                          state_name: New York
                          zip: 12345
                        - city: Brooklyn
                          city_id: 3654
                          country_code: US
                          country_name: United States
                          state_name: New York
                          zip: 11234
                        - city: Annawan
                          city_id: 26301
                          country_code: US
                          country_name: United States
                          state_name: Illinois
                          zip: 61234
                        - city: Parkville
                          city_id: 8439
                          country_code: US
                          country_name: United States
                          state_name: Maryland
                          zip: 21234
                        - city: Downsville
                          city_id: 30419
                          country_code: US
                          country_name: United States
                          state_name: Louisiana
                          zip: 71234
                    message: Suceess
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: {}
                  message:
                    type: string
              examples:
                If token is missing in headers:
                  value:
                    data: []
                    message: "Mandatory parameter 'token' is missing."
                If zipcode is not valid:
                  value:
                    data: []
                    message: '"zipcode" must be a safe number'
        '401':
          description: Authentication Failed
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                If token is wrong:
                  value:
                    data: []
                    message: Invalid auth token provided
        '402':
          description: Request Failed
        '500':
          description: Internal Server Error
      operationId: get-zipcode
      description: |-
        ### GET Method -
        This API returns all the cities for the given **zipcode in query params** under the **provider token in headers**
      parameters:
        - schema:
            type: string
          in: query
          required: true
          name: zipcode
          description: ZipCode
        - schema:
            type: string
          in: header
          name: token
          required: true
          description: A Provider Token
    parameters: []
components:
  schemas: {}
servers:
  - url: 'https://api.denefits.com:8005'
